[project]
name = "PatchSentryx"
version = "0.1.0"
description = "Vulnerability Identification with LLMs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.27.6",
]
dynamic = ["version"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]
