[project]
name = "core"
version = "0.1.0"
description = "Core functionality for PatchSentryx"
requires-python = ">=3.12"
dependencies = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]